[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
openbudget = "RECtBgp43nvj5inPVW7qo1YN95RwXaYDxLX4dvuJXFY"

[programs.devnet]
openbudget = "RECtBgp43nvj5inPVW7qo1YN95RwXaYDxLX4dvuJXFY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/REC-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
